$(document).ready(function() {
    const valueMappings = {
        '#loanWork': '#lwtype',
        '#ltype': '#loantype, #loan1type',
        '#fname': '#fullName, #full1Name, #full2Name, #full3Name',
        '#myage': '#myAge, #my1Age',
        '#pdist': '#pDist, #p1Dist, #p2Dist',
        '#tdist': '#tDist, #t1Dist, #t2Dist',
        '#pgapa': '#pGapa, #p1Gapa, #p2Gapa',
        '#pogapa': '#toGapa, #to1Gapa, #to2Gapa',
        '#pogapaA': '#poGapa, #po1Gapa',
        '#pward': '#pWard, #p1Ward, #p2Ward',
        '#tgapaz': '#tGapa, #t1Gapa, #t2Gapa',
        '#togapa': '#toGapa, #to1Gapa, #to2Gapa',
        '#tward': '#tWard, #t1Ward, #t2Ward',
        '#grandpa': '#grandPa, #grand1Pa, #grand2Pa',
        '#father': '#Father, #Father1, #Father2',
        '#wifehub': '#wifeHub, #wife1Hub, #wife2Hub',
        '#todaydate': '#todayDate, #today1Date, #today2Date',
        '#mob': '#Mob',
        '#mrno': '#mrNo',
        '#mrcr': '#mr2cr',
        '#intPerc': '#PercInt',
        '#paidyear': '#paidYear',
        '#paidmonth': '#paidMonth',
        '#paidday': '#paidDay',
        '#mperiodtype': '#mPeriodType',
        '#memo21': '#Ememo21, #gMemo18',
        '#memoz21': '#gMemo1',
        '#memo27': '#Ememo27, #gMemo24',
        '#memoz27': '#gMemo2',
        '#memo33': '#Ememo33, #gMemo28',
        '#memoz33': '#gMemo3',
        '#memo22a': '#Ememo22, #gMemo11',
        '#memo28a': '#Ememo28, #gMemo12',
        '#memo34a': '#Ememo34, #gMemo19',
        '#memo22b': '#gMemo13',
        '#memo28b': '#gMemo14',
        '#memo34b': '#gMemo20',
        '#togapa1': '#togapa7',
        '#togapa5': '#togapa8',
        '#togapa6': '#togapa9',
        '#togapa2': '#gMemo15',
        '#togapa3': '#gMemo21',
        '#togapa4': '#gMemo25',
        '#memo22d': '#gMemo16',
        '#memo28d': '#gMemo22',
        '#memo34d': '#gMemo26',
        '#memo23': '#Ememo23',
        '#memoz23': '#gMemo7',
        '#memo29': '#Ememo29',
        '#memoz29': '#gMemo8',
        '#memo35': '#Ememo35, #gMemo9',
        '#memoz35': '#gMemo9',
        '#memo24': '#Ememo24',
        '#memo30': '#Ememo30',
        '#memo36': '#Ememo36',
        '#memo25': '#Ememo25',
        '#memo31': '#Ememo31',
        '#memo37': '#Ememo37',
        '#todayyear': '#TodayYear',
        '#todaymonth': '#TodayMonth',
        '#todayday': '#TodayDay',
        '#weekday': '#TodayWeekDay',
        '#memoz22a': '#gMemoz11',
        '#memoz22b': '#gMemoz13',
        '#togapaz1': '#togapaz7',
        '#togapaz2': '#gMemoz15',
        '#memoz22d': '#gMemoz16',
        '#memoz28a': '#gMemozs11',
        '#memoz28b': '#gMemozs13',
        '#togapaz5': '#togapazs7',
        '#togapaz3': '#gMemozs15',
        '#memoz28d': '#gMemozs16',
        '#memoz34a': '#gMemozp11',
        '#memoz34b': '#gMemozp13',
        '#togapaz6': '#togapazp7',
        '#togapaz4': '#gMemozp15',
        '#memoz34d': '#gMemozp16'
    };

    // Dynamically bind change events
    Object.entries(valueMappings).forEach(([source, targets]) => {
        $(source).on('change', function() {
            const value = $(this).val();
            $(targets).html(value);
        });
    });
});